name: Quantum Sikh News Network
favicon: null
layout_spectrum: 0.19542713603004813
typography_spectrum: 0.945567739661783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21096862549893558
  lightness: 0.2822308517061174
  saturation: 0.18481312110088766
  rhythmicContrast: 0.9143818668089807
purpose: []
